name: video_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11
  country_picker: ^2.0.16
  flutter_riverpod: ^2.0.2
  image_picker: ^0.8.6
  flutter_contacts: ^1.1.5
  # uuid: ^3.0.6
  # intl: ^0.17.0
  # cached_network_image: ^3.2.1
  # cached_video_player: ^2.0.3
  # emoji_picker_flutter: ^1.3.0
  # enough_giphy_flutter: ^0.3.0
  # flutter_sound: ^9.2.13
  # path_provider: ^2.0.11
  # permission_handler: ^9.2.0
  # audioplayers: ^1.0.1
  # swipe_to: ^1.0.2
  # story_view: ^0.13.2
  # agora_uikit: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
